services:
  mosquitto:
    # MQTT broker
    image: eclipse-mosquitto:2.0.21
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./config_files/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped

  iot_simulator:
    build: ./IoT
    container_name: iot_simulator
    depends_on:
      - mosquitto
    restart: on-failure
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=parking/
    volumes:
      - ./IoT/parking_data.txt:/app/parking_data.txt
  
  parking_db:
    image: mongo:8
    container_name: parking_db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    #   - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
      - "27017:27017"
    volumes:
      - parking_database:/data/db
      - ./config_files/mongodb:/docker-entrypoint-initdb.d:ro
  
volumes:
  mosquitto_data:
  parking_database: